
import { Language } from './types';

export const APP_CONFIG = {
  name: "Planify",
  version: "7.2.0",
  suffix: "AI",
  fullName: "PlanifyAI Pro"
};

export const TRANSLATIONS = {
  uz: {
    dashboard: "Boshqaruv Paneli",
    calendar: "Taqvim",
    today: "Bugun",
    tasks: "Vazifalar",
    habits: "Odatlar",
    finance: "Moliya",
    aiCoach: "AI Murabbiy",
    aiPlanner: "AI Rejalashtiruvchi",
    profile: "Profil",
    welcome: "Xush kelibsiz",
    todaysFocus: "Bugungi Maqsad",
    upcomingDeadlines: "Yaqinlashayotgan Muddatlar",
    habitProgress: "Odatlar Rivoji",
    addTask: "Vazifa qo'shish",
    newHabit: "Yangi odat yaratish...",
    priority: "Muhimlik",
    low: "Past",
    medium: "O'rta",
    high: "Yuqori",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    completed: "Bajarildi",
    pending: "Kutilmoqda",
    aiPrompt: "Mening samaradorligimni tahlil qiling va maslahat bering.",
    aiLoading: "AI tahlil qilmoqda...",
    streak: "seriya",
    noTasks: "Bugun uchun vazifalar yo'q.",
    timeBlock: "Vaqt bloki",
    askAi: "AI dan so'rang",
    titlePlaceholder: "Sarlavha...",
    descPlaceholder: "Tavsif (ixtiyoriy)",
    tagPlaceholder: "Tag (Enter bosing)",
    noUpcoming: "Yaqinlashayotgan vazifalar yo'q.",
    viewAll: "Barchasini ko'rish",
    // Auth
    login: "Kirish",
    signup: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",
    noAccount: "Hisobingiz yo'qmi?",
    haveAccount: "Hisobingiz bormi?",
    authError: "Xatolik yuz berdi",
    signOut: "Chiqish",
    loading: "Yuklanmoqda...",
    // Admin & Subscription
    adminPanel: "Admin Panel",
    accessDenied: "Kirish cheklangan",
    subscriptionExpired: "Hisob bloklangan",
    subscriptionDesc: "Ilovadan foydalanish uchun hisobingiz faol bo'lishi kerak. Iltimos, administratorga murojaat qiling.",
    daysLeft: "kun qoldi",
    grantAccess: "Kirish ruxsatini berish",
    active: "Faol",
    inactive: "Faol emas",
    role: "Rol",
    expiresAt: "Tugash muddati",
    users: "Foydalanuvchilar",
    contactAdmin: "Adminga murojaat qiling",
    subscribeTelegram: "Telegram orqali bog'lanish",
    founder: "Asoschi: Akramov Azamat",
    actions: "Amallar",
    searchPlaceholder: "Qidirish...",
    // Analytics
    analytics: "Tahlil",
    tracker: "Kuzatuv",
    completionRate: "Bajarilish Foizi",
    last30Days: "Oxirgi 30 kun",
    consistency: "Barqarorlik",
    heatmap: "Yillik Faollik",
    successRate: "Muvaffaqiyat",
    totalCompletions: "Jami bajarilgan",
    bestStreak: "Eng yaxshi seriya",
    // UI Headers
    proAssistant: "PRO YORDAMCHI",
    aiAssistant: "AI YORDAMCHI",
    menuHeader: "MENYU",
    accountHeader: "PROFIL",
    levelLabel: "DARAJA",
    xpLabel: "XP",
    remaining: "vazifa qoldi",
    allClear: "Barchasi tayyor",
    readyStatus: "TAYYOR",
    // New Features
    pomodoro: "Pomodoro Taymer",
    focusSession: "Fokus Seansi",
    startFocus: "Boshlash",
    pause: "To'xtatish",
    resume: "Davom etish",
    stop: "Tugatish",
    takeBreak: "Dam olish vaqti!",
    brainDump: "Fikrlar Ombori",
    notePlaceholder: "Fikringizni yozing...",
    convertToTask: "Vazifaga aylantirish",
    xp: "XP",
    level: "Daraja",
    levelUp: "Daraja oshdi!",
    dailyBriefing: "Kunlik Brifing",
    generateBriefing: "Brifing yaratish",
    briefingLoading: "Kunlik rejangiz tahlil qilinmoqda...",
    // Habits Specific
    checkToday: "Bugun bajarish",
    doneToday: "Bajarildi!",
    history: "Tarix",
    currentStreak: "Joriy seriya",
    startHabit: "Odatni boshlash",
    monitoring: "MONITORING",
    thisWeek: "Shu hafta",
    lastWeek: "O'tgan hafta",
    ago: "oldin",
    later: "keyin",
    // Profile Specific
    accountSettings: "Hisob sozlamalari",
    personalInfo: "Shaxsiy ma'molumotlar",
    appLanguage: "Ilova tili",
    subscriptionPlan: "Obuna holati",
    planFree: "Oddiy foydalanuvchi",
    planPro: "Pro Foydalanuvchi",
    memberSince: "A'zo bo'lgan sana",
    statistics: "Statistika",
    totalTasks: "Jami vazifalar",
    activeHabits: "Faol odatlar",
    currentLevel: "Joriy daraja",
    unlimitedAccess: "Cheksiz ruxsat",
    // AI Planner
    aiPlannerTitle: "AI Planner",
    aiPlannerSubtitle: "Bugun nimalar qilmoqchisiz? Ayting yoki yozing...",
    listening: "Eshitilmoqda...",
    createPlan: "Reja tuzish",
    planCreated: "Reja muvaffaqiyatli tuzildi!",
    allTasksAdded: "Barcha vazifalar qo'shildi",
    tryVoice: "Ovozli buyruqni sinab ko'ring",
    voiceExample: "Masalan: Ertaga soat 9 da majlis bor, keyin bozor qilishim kerak.",
    processing: "AI rejalashtirmoqda...",
    generatedTasks: "Yaratilgan vazifalar",
    addAllTasks: "Barchasini qo'shish",
    // Finance
    financeHub: "FinanceHub",
    financeSubtitle: "Mukammal Moliya Portali",
    totalBalance: "Umumiy Balans",
    income: "Kirim",
    expense: "Chiqim",
    addTransaction: "Kirim/Chiqim qo'shish",
    amount: "Summa",
    category: "Kategoriya",
    transactionTitle: "Nomi",
    type: "Turi",
    aiFinanceAdvice: "Moliyaviy maslahat oling",
    recentTransactions: "Oxirgi o'tkazmalar",
    noTransactions: "Hozircha o'tkazmalar yo'q",
    spendingTrend: "Xarajatlar Trendi",
    smartWallet: "Aqlli Hamyon Tizimi",
    new: "Yangi",
    saveTransaction: "O'tkazmani saqlash",
    goals: "Maqsadlar",
    debts: "Qarzlar"
  },
  ru: {
    dashboard: "Панель управления",
    calendar: "Календарь",
    today: "Сегодня",
    tasks: "Задачи",
    habits: "Привычки",
    finance: "Финансы",
    aiCoach: "ИИ Коуч",
    aiPlanner: "ИИ Планировщик",
    profile: "Профиль",
    welcome: "Добро пожаловать",
    todaysFocus: "Главная цель",
    upcomingDeadlines: "Ближайшие дедлайны",
    habitProgress: "Прогресс привычек",
    addTask: "Добавить задачу",
    newHabit: "Создать новую привычку...",
    priority: "Приоритет",
    low: "Низкий",
    medium: "Средний",
    high: "Высокий",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    completed: "Выполнено",
    pending: "В ожидании",
    aiPrompt: "Проанализируй мою продуктивность и дай совет.",
    aiLoading: "ИИ анализирует...",
    streak: "серия",
    noTasks: "На сегодня задач нет.",
    timeBlock: "Временной блок",
    askAi: "Спросить ИИ",
    titlePlaceholder: "Название...",
    descPlaceholder: "Описание (опционально)",
    tagPlaceholder: "Тег (Нажмите Enter)",
    noUpcoming: "Нет предстоящих задач.",
    viewAll: "Посмотреть все",
    // Auth
    login: "Войти",
    signup: "Регистрация",
    email: "Email",
    password: "Пароль",
    noAccount: "Нет аккаунта?",
    haveAccount: "Есть аккаунт?",
    authError: "Произошла ошибка",
    signOut: "Выйти",
    loading: "Загрузка...",
    // Admin & Subscription
    adminPanel: "Админ Панель",
    accessDenied: "Доступ запрещен",
    subscriptionExpired: "Аккаунт заблокирован",
    subscriptionDesc: "Для использования приложения ваш аккаунт должен быть активен. Пожалуйста, свяжитесь с администратором.",
    daysLeft: "дней осталось",
    grantAccess: "Дать доступ",
    active: "Активен",
    inactive: "Неактивен",
    role: "Роль",
    expiresAt: "Истекает",
    users: "Пользователи",
    contactAdmin: "Свяжитесь с админом",
    subscribeTelegram: "Связаться через Telegram",
    founder: "Основатель: Акрамов Азамат",
    actions: "Действия",
    searchPlaceholder: "Поиск...",
    // Analytics
    analytics: "Аналитика",
    tracker: "Трекер",
    completionRate: "Процент выполнения",
    last30Days: "Последние 30 дней",
    consistency: "Стабильность",
    heatmap: "Годовая активность",
    successRate: "Успешность",
    totalCompletions: "Всего выполнено",
    bestStreak: "Лучшая серия",
    // UI Headers
    proAssistant: "PRO ПОМОЩНИК",
    aiAssistant: "ИИ ПОМОЩНИК",
    menuHeader: "МЕНЮ",
    accountHeader: "ПРОФИЛЬ",
    levelLabel: "УРОВЕНЬ",
    xpLabel: "XP",
    remaining: "задач осталось",
    allClear: "Все готово",
    readyStatus: "ГОТОВ",
    // New Features
    pomodoro: "Таймер Помидора",
    focusSession: "Сессия Фокуса",
    startFocus: "Начать",
    pause: "Пауза",
    resume: "Продолжить",
    stop: "Стоп",
    takeBreak: "Время перерыва!",
    brainDump: "Свалка идей",
    notePlaceholder: "Запишите мысль...",
    convertToTask: "В задачу",
    xp: "XP",
    level: "Уровень",
    levelUp: "Уровень повышен!",
    dailyBriefing: "Ежедневный брифинг",
    generateBriefing: "Создать брифинг",
    briefingLoading: "Анализ плана на день...",
    // Habits Specific
    checkToday: "Выполнить сегодня",
    doneToday: "Выполнено!",
    history: "История",
    currentStreak: "Текущая серия",
    startHabit: "Начать привычку",
    monitoring: "МОНИТОРИНГ",
    thisWeek: "Эта неделя",
    lastWeek: "Прошлая неделя",
    ago: "назад",
    later: "спустя",
    // Profile Specific
    accountSettings: "Настройки аккаунта",
    personalInfo: "Личная информация",
    appLanguage: "Язык приложения",
    subscriptionPlan: "Статус подписки",
    planFree: "Обычный пользователь",
    planPro: "Pro Пользователь",
    memberSince: "Дата регистрации",
    statistics: "Статистика",
    totalTasks: "Всего задач",
    activeHabits: "Активные привычки",
    currentLevel: "Текущий уровень",
    unlimitedAccess: "Безлимитный доступ",
    // AI Planner
    aiPlannerTitle: "AI Планировщик",
    aiPlannerSubtitle: "Скажите, что вы планируете на сегодня...",
    listening: "Слушаю...",
    createPlan: "Создать план",
    planCreated: "План успешно создан!",
    allTasksAdded: "Все задачи добавлены",
    tryVoice: "Попробуйте голосовой ввод",
    voiceExample: "Пример: Завтра в 9 утра совещание, потом нужно купить продукты.",
    processing: "ИИ планирует...",
    generatedTasks: "Созданные задачи",
    addAllTasks: "Добавить все",
    // Finance
    financeHub: "FinanceHub",
    financeSubtitle: "Идеальный Финансовый Портал",
    totalBalance: "Общий Баланс",
    income: "Доход",
    expense: "Расход",
    addTransaction: "Добавить операцию",
    amount: "Сумма",
    category: "Категория",
    transactionTitle: "Название",
    type: "Тип",
    aiFinanceAdvice: "Получить фин. совет",
    recentTransactions: "Недавние транзакции",
    noTransactions: "Транзакций пока нет",
    spendingTrend: "Тренд расходов",
    smartWallet: "Умная Система Кошелька",
    new: "Новый",
    saveTransaction: "Сохранить перевод",
    goals: "Цели",
    debts: "Долги"
  }
};

export const HABIT_COLORS = [
  'bg-emerald-500',
  'bg-indigo-500',
  'bg-rose-500',
  'bg-amber-500',
  'bg-sky-500',
  'bg-purple-500',
  'bg-pink-500'
];

export const TIME_SLOTS = [
  "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", 
  "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", 
  "18:00", "19:00", "20:00", "21:00", "22:00"
];

export const EXPENSE_CATEGORIES = [
  { id: 'food', label: 'Oziq-ovqat', icon: '🍔', color: 'bg-orange-500' },
  { id: 'transport', label: 'Transport', icon: '🚕', color: 'bg-blue-500' },
  { id: 'shopping', label: 'Xaridlar', icon: '🛍️', color: 'bg-pink-500' },
  { id: 'bills', label: 'To\'lovlar', icon: '💡', color: 'bg-red-500' },
  { id: 'entertainment', label: 'Ko\'ngilochar', icon: '🎬', color: 'bg-purple-500' },
  { id: 'other', label: 'Boshqa', icon: '📦', color: 'bg-slate-500' }
];

export const INCOME_CATEGORIES = [
  { id: 'salary', label: 'Oylik', icon: '💰', color: 'bg-emerald-500' },
  { id: 'freelance', label: 'Freelance', icon: '💻', color: 'bg-indigo-500' },
  { id: 'gift', label: 'Sovg\'a', icon: '🎁', color: 'bg-pink-500' },
  { id: 'other', label: 'Boshqa', icon: '📦', color: 'bg-slate-500' }
];
